-- The market schema itself is created out of band by a superuser, because the
-- app role deliberately lacks CREATE on the database. Migrations only create
-- objects inside the schema this service owns.

-- Current order snapshot. One partition per region, created at runtime once the
-- region set is resolved from the SDE.
--
-- Columns are the ESI payload plus region_id and nothing else. Derived values such
-- as a trade-hub range flag, and values needing an authenticated token such as
-- character_id, deliberately do not exist: both belong to the reader.
CREATE TABLE IF NOT EXISTS market.orders (
    region_id     bigint        NOT NULL,
    order_id      bigint        NOT NULL,
    type_id       bigint        NOT NULL,
    location_id   bigint        NOT NULL,
    system_id     bigint        NOT NULL,
    is_buy_order  boolean       NOT NULL,
    -- ESI sends at most two decimals and float sums drift, so ISK is numeric.
    price         numeric(20,2) NOT NULL,
    -- Tritanium-class orders exceed 32 bits.
    volume_remain bigint        NOT NULL,
    volume_total  bigint        NOT NULL,
    min_volume    integer       NOT NULL,
    duration      integer       NOT NULL,
    "range"       text          NOT NULL,
    issued        timestamptz   NOT NULL,
    -- A partitioned table's unique index must contain the partition key, so
    -- order_id alone cannot be the key. order_id is still globally unique.
    PRIMARY KEY (region_id, order_id)
) PARTITION BY LIST (region_id);

CREATE INDEX IF NOT EXISTS orders_region_buy_type_price
    ON market.orders (region_id, is_buy_order, type_id, price);
CREATE INDEX IF NOT EXISTS orders_type_region_buy_price
    ON market.orders (type_id, region_id, is_buy_order, price);
-- For sell orders the consumer's hub-range test is exactly location_id = <hub
-- station>, and sell orders are ~70% of the table.
CREATE INDEX IF NOT EXISTS orders_region_location_buy_type_price
    ON market.orders (region_id, location_id, is_buy_order, type_id, price);
CREATE INDEX IF NOT EXISTS orders_region_issued
    ON market.orders (region_id, issued);

-- Daily history from the EVE Ref dataset. One partition per year, created at runtime.
CREATE TABLE IF NOT EXISTS market.history (
    region_id          bigint        NOT NULL,
    type_id            bigint        NOT NULL,
    date               date          NOT NULL,
    average            numeric(20,2) NOT NULL,
    highest            numeric(20,2) NOT NULL,
    lowest             numeric(20,2) NOT NULL,
    volume             bigint        NOT NULL,
    order_count        bigint        NOT NULL,
    -- When EVE Ref scraped this row. Drives the incremental import watermark.
    http_last_modified timestamptz,
    PRIMARY KEY (region_id, type_id, date)
) PARTITION BY RANGE (date);

CREATE INDEX IF NOT EXISTS history_region_date
    ON market.history (region_id, date);

-- The contract with the reader, which polls refreshed_at to trigger its own work.
-- Adding columns here is safe; renaming or removing one breaks the reader.
CREATE TABLE IF NOT EXISTS market.region_status (
    region_id          bigint      PRIMARY KEY,
    region_name        text        NOT NULL,
    priority           integer     NOT NULL,
    refreshed_at       timestamptz,
    expires            timestamptz,
    last_modified      timestamptz,
    pages              integer,
    order_count        bigint,
    consecutive_errors integer     NOT NULL DEFAULT 0,
    last_error         text,
    last_error_at      timestamptz
);

-- Operational history, pruned on a retention setting.
CREATE TABLE IF NOT EXISTS market.ingest_log (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id        bigint      NOT NULL,
    cycle_started_at timestamptz NOT NULL,
    pages            integer,
    tokens_spent     integer,
    remaining_after  integer,
    -- fetch_ms and copy_ms overlap: pages stream into Postgres while later pages
    -- are still in flight. They are two views of one window, not stages to sum.
    fetch_ms         integer,
    copy_ms          integer,
    apply_ms         integer,
    verify_ms        integer,
    rows_inserted    integer,
    rows_updated     integer,
    rows_deleted     integer,
    duplicate_rows   integer,
    outcome          text        NOT NULL,
    deferred_reason  text
);

-- Range scan for the prune job.
CREATE INDEX IF NOT EXISTS ingest_log_cycle_started_at
    ON market.ingest_log (cycle_started_at);

-- EVE Ref day bookkeeping. A day file keeps growing for about four days, so the
-- watermark records how far we have already imported.
CREATE TABLE IF NOT EXISTS market.everef_day (
    day          date        PRIMARY KEY,
    totals_count bigint      NOT NULL,
    -- Cumulative across every re-import of this day, not the number of rows the
    -- day holds: a day fills in waves, so it is upserted more than once.
    rows_upserted bigint     NOT NULL,
    watermark    timestamptz,
    imported_at  timestamptz NOT NULL
);
